var employee = employee || {};

employee.data = [
    {
        "EmployeeCode":"NV01",
        "EmployeeName":"Do Van Hai", 
        "Gender": 1,
        "DateOfBirth": "28/01/2000",
        "IdentityNumber": "036200011834",
        "EmployeePosition":"Fresher",
        "DepartmentId": "Viện đào tạoádddddddddddddddddddsddddddddddddd",
        "BankAccountNumber":"13562288455",
        "BankName":"BIDV",
        "BankBranchName": "DH GTVT",
    },
    {
        "EmployeeCode":"NV01",
        "EmployeeName":"Do Van Hai", 
        "Gender": 1,
        "DateOfBirth": "28/01/2000",
        "IdentityNumber": "036200011834",
        "EmployeePosition":"Fresher",
        "DepartmentId": "Viện đào tạo",
        "BankAccountNumber":"13562288455",
        "BankName":"BIDV",
        "BankBranchName": "DH GTVT",
    },
    {
        "EmployeeCode":"NV01",
        "EmployeeName":"Do Van Hai", 
        "Gender": 1,
        "DateOfBirth": "28/01/2000",
        "IdentityNumber": "036200011834",
        "EmployeePosition":"Fresher",
        "DepartmentId": "Viện đào tạo",
        "BankAccountNumber":"13562288455",
        "BankName":"BIDV",
        "BankBranchName": "DH GTVT",
    },
    {
        "EmployeeCode":"NV01",
        "EmployeeName":"Do Van Hai", 
        "Gender": 1,
        "DateOfBirth": "28/01/2000",
        "IdentityNumber": "036200011834",
        "EmployeePosition":"Fresher",
        "DepartmentId": "Viện đào tạo",
        "BankAccountNumber":"13562288455",
        "BankName":"BIDV",
        "BankBranchName": "DH GTVT",
    },
    {
        "EmployeeCode":"NV01",
        "EmployeeName":"Do Van Hai", 
        "Gender": 1,
        "DateOfBirth": "28/01/2000",
        "IdentityNumber": "036200011834",
        "EmployeePosition":"Fresher",
        "DepartmentId": "Viện đào tạo",
        "BankAccountNumber":"13562288455",
        "BankName":"BIDV",
        "BankBranchName": "DH GTVT",
    },
    {
        "EmployeeCode":"NV01",
        "EmployeeName":"Do Van Hai", 
        "Gender": 1,
        "DateOfBirth": "28/01/2000",
        "IdentityNumber": "036200011834",
        "EmployeePosition":"Fresher",
        "DepartmentId": "Viện đào tạo",
        "BankAccountNumber":"13562288455",
        "BankName":"BIDV",
        "BankBranchName": "DH GTVT",
    },
    {
        "EmployeeCode":"NV01",
        "EmployeeName":"Do Van Hai", 
        "Gender": 1,
        "DateOfBirth": "28/01/2000",
        "IdentityNumber": "036200011834",
        "EmployeePosition":"Fresher",
        "DepartmentId": "Viện đào tạo",
        "BankAccountNumber":"13562288455",
        "BankName":"BIDV",
        "BankBranchName": "DH GTVT",
    },
    {
        "EmployeeCode":"NV01",
        "EmployeeName":"Do Van Hai", 
        "Gender": 1,
        "DateOfBirth": "28/01/2000",
        "IdentityNumber": "036200011834",
        "EmployeePosition":"Fresher",
        "DepartmentId": "Viện đào tạo",
        "BankAccountNumber":"13562288455",
        "BankName":"BIDV",
        "BankBranchName": "DH GTVT",
    },
    {
        "EmployeeCode":"NV01",
        "EmployeeName":"Do Van Hai", 
        "Gender": 1,
        "DateOfBirth": "28/01/2000",
        "IdentityNumber": "036200011834",
        "EmployeePosition":"Fresher",
        "DepartmentId": "Viện đào tạo",
        "BankAccountNumber":"13562288455",
        "BankName":"BIDV",
        "BankBranchName": "DH GTVT",
    },
    {
        "EmployeeCode":"NV01",
        "EmployeeName":"Do Van Hai", 
        "Gender": 1,
        "DateOfBirth": "28/01/2000",
        "IdentityNumber": "036200011834",
        "EmployeePosition":"Fresher",
        "DepartmentId": "Viện đào tạo",
        "BankAccountNumber":"13562288455",
        "BankName":"BIDV",
        "BankBranchName": "DH GTVT",
    },
    {
        "EmployeeCode":"NV01",
        "EmployeeName":"Do Van Hai", 
        "Gender": 1,
        "DateOfBirth": "28/01/2000",
        "IdentityNumber": "036200011834",
        "EmployeePosition":"Fresher",
        "DepartmentId": "Viện đào tạo",
        "BankAccountNumber":"13562288455",
        "BankName":"BIDV",
        "BankBranchName": "DH GTVT",
    },
    {
        "EmployeeCode":"NV01",
        "EmployeeName":"Do Van Hai", 
        "Gender": 1,
        "DateOfBirth": "28/01/2000",
        "IdentityNumber": "036200011834",
        "EmployeePosition":"Fresher",
        "DepartmentId": "Viện đào tạo",
        "BankAccountNumber":"13562288455",
        "BankName":"BIDV",
        "BankBranchName": "DH GTVT",
    },
    {
        "EmployeeCode":"NV01",
        "EmployeeName":"Do Van Hai", 
        "Gender": 1,
        "DateOfBirth": "28/01/2000",
        "IdentityNumber": "036200011834",
        "EmployeePosition":"Fresher",
        "DepartmentId": "Viện đào tạo",
        "BankAccountNumber":"13562288455",
        "BankName":"BIDV",
        "BankBranchName": "DH GTVT",
    },
    {
        "EmployeeCode":"NV01",
        "EmployeeName":"Do Van Hai", 
        "Gender": 1,
        "DateOfBirth": "28/01/2000",
        "IdentityNumber": "036200011834",
        "EmployeePosition":"Fresher",
        "DepartmentId": "Viện đào tạo",
        "BankAccountNumber":"13562288455",
        "BankName":"BIDV",
        "BankBranchName": "DH GTVT",
    },
    {
        "EmployeeCode":"NV01",
        "EmployeeName":"Do Van Hai", 
        "Gender": 1,
        "DateOfBirth": "28/01/2000",
        "IdentityNumber": "036200011834",
        "EmployeePosition":"Fresher",
        "DepartmentId": "Viện đào tạo",
        "BankAccountNumber":"13562288455",
        "BankName":"BIDV",
        "BankBranchName": "DH GTVT",
    },
]

export default employee